apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-python-api
  namespace: ecom-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-python-api
  template:
    metadata:
      labels:
        app: ecom-python-api
    spec:
      containers:
        - name: ecom-python-api
          image: ecom-python-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres-17-postgresql.postgresql:5432/ecom_python" 